<!-- Language file for English -->

Loc_AskInstall = "<p><h3>You do not have the latest Heroes & Generals plugin installed.</h3>\nYou will not be able to play the action game without it.</p>\n<p>Would you like to install it now?</p>";
Loc_AskInstallChrome = "<p><h3>The Heroes & Generals action client is not installed.</h3>\nYou will not be able to play the action game without it.</p>\n<p>Would you like to install it now?</p>";
Loc_AskInstallExt = "<p><h3>You do not have the latest <a href='https://chrome.google.com/webstore/detail/heroes-generals/gbophcdhblbipoaacgchllkobdaolpge'>Chrome extension</a> for Heroes & Generals installed.</h3>\nYou will not be able to play the action game from Chrome without it.</p>\n<p>Would you like to install it now?</p>";
Loc_Continue = "Continue";
Loc_InstallExtInstructions_Chrome = "<p><h3>The extension installer will now pop up</h3></p>\n<p class='sm'>If it does not start automatically, please click <a href='https://chrome.google.com/webstore/detail/heroes-generals/gbophcdhblbipoaacgchllkobdaolpge'>here</a></p>\n<ol class='sm'>\n<li>Once the extension has been installed, refresh the page or press continue below to proceed with the installation of the game.</li>\n</ol>";
Loc_InstallInstructions_Chrome = "<p><h3>The installer will now download</h3></p>\n<p class='sm'>If it does not start automatically, please click <a href='{0}'>here</a></p>\n<ol class='sm'>\n<li>When warning dialog appears at the bottom of your browser, click <b>Save</b>.</li>\n<li>When download dialog appears at the bottom of your browser, <b>double-click</b> the file.</li>\n<li>When Security Warning dialog box appears, click <b>Run</b>.</li>\n<li>When User Account Control dialog box appears, click <b>Yes</b>.</li>\n</ol>";
Loc_InstallInstructions_Firefox = "<p><h3>The installer will now download</h3></p>\n<p class='sm'>If it does not start automatically, please click <a href='{0}'>here</a></p>\n<ol class='sm'>\n<li>When Opening dialog box appears, click <b>Save File</b>.</li>\n<li>When Downloads window appears, <b>double-click</b> the file.</li>\n<li>When Security Warning dialog box appears, click <b>Run</b>.</li>\n<li>When User Account Control dialog box appears, click <b>Yes</b>.</li>\n</ol>";
Loc_InstallInstructions_IE = "<p><h3>The installer will now download</h3></p>\n<p class='sm'>If it does not start automatically, please click <a href='{0}'>here</a></p>\n<ol class='sm'>\n<li>When File Download dialog box appears, click <b>Run</b>. Security scan will run automatically.</li>\n<li>When User Account Control dialog box appears, click <b>Yes</b>.</li>\n</ol>\n";
Loc_InstallInstructions_Other = "<p><h3>The installer will now download</h3></p>\n<p class='sm'>If it does not start automatically, please click <a href='{0}'>here</a></p>\n<p class='sm'>After the download, please launch:</p>\n<p class='sm'>HeroesAndGenerals-setup.exe</p>";
Loc_Loading = "Loading...";
Loc_No = "No";
Loc_NoMoreBrowser = "<p class=\"intro\">To make your gaming experience even more awesome, Heroes & Generals has become a client-based game, and can no longer be played through a web browser.</p><p>The installer for the <b>STAND-ALONE</b> client is available <h1><a href=\"{0}\">here</a></h1></p>";
Loc_UnsupportedBrowser = "<p><h3>Unfortunately you are using a browser, we currently do not support.</h3></p>\n<p>Heroes & Generals requires <a href='http://firefox.com'>Firefox</a>, <a href='http://www.google.com/chrome'>Google Chrome</a> or <a href='http://ie.microsoft.com'>Internet Explorer</a> (32-bit versions only.)</p>\n<p><font size='-1'>You <em>may</em> be able to play the strategy game in other browsers, but we make no promises.</font></p>\n<p><font size='-1'>If you want to skip the action game and try, press continue below.</font></p>";
Loc_UnsupportedOS = "<p><h3>Heroes & Generals requires Windows.</h3></p>\n<p>Parts of Heroes & Generals  only runs on Windows. You can play the campaign part of the game on other platforms, but not the shooter game</p>\n<p><font size='-1'>If you want to skip the action game and try, press continue below.</font></p>";
Loc_Yes = "Yes";